// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.21.12
// source: api/rag/v1/rag.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IndexContentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url     string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *IndexContentRequest) Reset() {
	*x = IndexContentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rag_v1_rag_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IndexContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexContentRequest) ProtoMessage() {}

func (x *IndexContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rag_v1_rag_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexContentRequest.ProtoReflect.Descriptor instead.
func (*IndexContentRequest) Descriptor() ([]byte, []int) {
	return file_api_rag_v1_rag_proto_rawDescGZIP(), []int{0}
}

func (x *IndexContentRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *IndexContentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type IndexContentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *IndexContentResponse) Reset() {
	*x = IndexContentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rag_v1_rag_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IndexContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexContentResponse) ProtoMessage() {}

func (x *IndexContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rag_v1_rag_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexContentResponse.ProtoReflect.Descriptor instead.
func (*IndexContentResponse) Descriptor() ([]byte, []int) {
	return file_api_rag_v1_rag_proto_rawDescGZIP(), []int{1}
}

type RetrieveContextRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url   string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Query string `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *RetrieveContextRequest) Reset() {
	*x = RetrieveContextRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rag_v1_rag_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetrieveContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveContextRequest) ProtoMessage() {}

func (x *RetrieveContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rag_v1_rag_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveContextRequest.ProtoReflect.Descriptor instead.
func (*RetrieveContextRequest) Descriptor() ([]byte, []int) {
	return file_api_rag_v1_rag_proto_rawDescGZIP(), []int{2}
}

func (x *RetrieveContextRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *RetrieveContextRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type RetrieveContextResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContextChunks []string `protobuf:"bytes,1,rep,name=context_chunks,json=contextChunks,proto3" json:"context_chunks,omitempty"`
}

func (x *RetrieveContextResponse) Reset() {
	*x = RetrieveContextResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rag_v1_rag_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetrieveContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveContextResponse) ProtoMessage() {}

func (x *RetrieveContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rag_v1_rag_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveContextResponse.ProtoReflect.Descriptor instead.
func (*RetrieveContextResponse) Descriptor() ([]byte, []int) {
	return file_api_rag_v1_rag_proto_rawDescGZIP(), []int{3}
}

func (x *RetrieveContextResponse) GetContextChunks() []string {
	if x != nil {
		return x.ContextChunks
	}
	return nil
}

var File_api_rag_v1_rag_proto protoreflect.FileDescriptor

var file_api_rag_v1_rag_proto_rawDesc = []byte{
	0x0a, 0x14, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x61, 0x67, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x61, 0x67,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x72, 0x61, 0x67, 0x2e, 0x76, 0x31, 0x22, 0x41,
	0x0a, 0x13, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x22, 0x16, 0x0a, 0x14, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x40, 0x0a, 0x16, 0x52, 0x65, 0x74,
	0x72, 0x69, 0x65, 0x76, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x22, 0x40, 0x0a, 0x17, 0x52,
	0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78,
	0x74, 0x5f, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x73, 0x32, 0xaf, 0x01,
	0x0a, 0x0a, 0x52, 0x41, 0x47, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4b, 0x0a, 0x0c,
	0x49, 0x6e, 0x64, 0x65, 0x78, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1b, 0x2e, 0x72,
	0x61, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x43, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x72, 0x61, 0x67, 0x2e,
	0x76, 0x31, 0x2e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x54, 0x0a, 0x0f, 0x52, 0x65, 0x74,
	0x72, 0x69, 0x65, 0x76, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x1e, 0x2e, 0x72,
	0x61, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x78, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x72,
	0x61, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x78, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x1e, 0x5a, 0x1c, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x6f,
	0x72, 0x74, 0x61, 0x6c, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x72, 0x61, 0x67, 0x2f, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_rag_v1_rag_proto_rawDescOnce sync.Once
	file_api_rag_v1_rag_proto_rawDescData = file_api_rag_v1_rag_proto_rawDesc
)

func file_api_rag_v1_rag_proto_rawDescGZIP() []byte {
	file_api_rag_v1_rag_proto_rawDescOnce.Do(func() {
		file_api_rag_v1_rag_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_rag_v1_rag_proto_rawDescData)
	})
	return file_api_rag_v1_rag_proto_rawDescData
}

var file_api_rag_v1_rag_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_rag_v1_rag_proto_goTypes = []interface{}{
	(*IndexContentRequest)(nil),     // 0: rag.v1.IndexContentRequest
	(*IndexContentResponse)(nil),    // 1: rag.v1.IndexContentResponse
	(*RetrieveContextRequest)(nil),  // 2: rag.v1.RetrieveContextRequest
	(*RetrieveContextResponse)(nil), // 3: rag.v1.RetrieveContextResponse
}
var file_api_rag_v1_rag_proto_depIdxs = []int32{
	0, // 0: rag.v1.RAGService.IndexContent:input_type -> rag.v1.IndexContentRequest
	2, // 1: rag.v1.RAGService.RetrieveContext:input_type -> rag.v1.RetrieveContextRequest
	1, // 2: rag.v1.RAGService.IndexContent:output_type -> rag.v1.IndexContentResponse
	3, // 3: rag.v1.RAGService.RetrieveContext:output_type -> rag.v1.RetrieveContextResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_rag_v1_rag_proto_init() }
func file_api_rag_v1_rag_proto_init() {
	if File_api_rag_v1_rag_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_rag_v1_rag_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IndexContentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rag_v1_rag_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IndexContentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rag_v1_rag_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetrieveContextRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rag_v1_rag_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetrieveContextResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_rag_v1_rag_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_rag_v1_rag_proto_goTypes,
		DependencyIndexes: file_api_rag_v1_rag_proto_depIdxs,
		MessageInfos:      file_api_rag_v1_rag_proto_msgTypes,
	}.Build()
	File_api_rag_v1_rag_proto = out.File
	file_api_rag_v1_rag_proto_rawDesc = nil
	file_api_rag_v1_rag_proto_goTypes = nil
	file_api_rag_v1_rag_proto_depIdxs = nil
}
