// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.21.12
// source: api/expert/v1/expert.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExpertType int32

const (
	ExpertType_EXPERT_TYPE_UNSPECIFIED ExpertType = 0
	ExpertType_EXPERT_TYPE_SIMPLE      ExpertType = 1
	ExpertType_EXPERT_TYPE_RAG         ExpertType = 2
)

// Enum value maps for ExpertType.
var (
	ExpertType_name = map[int32]string{
		0: "EXPERT_TYPE_UNSPECIFIED",
		1: "EXPERT_TYPE_SIMPLE",
		2: "EXPERT_TYPE_RAG",
	}
	ExpertType_value = map[string]int32{
		"EXPERT_TYPE_UNSPECIFIED": 0,
		"EXPERT_TYPE_SIMPLE":      1,
		"EXPERT_TYPE_RAG":         2,
	}
)

func (x ExpertType) Enum() *ExpertType {
	p := new(ExpertType)
	*p = x
	return p
}

func (x ExpertType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExpertType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_expert_v1_expert_proto_enumTypes[0].Descriptor()
}

func (ExpertType) Type() protoreflect.EnumType {
	return &file_api_expert_v1_expert_proto_enumTypes[0]
}

func (x ExpertType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExpertType.Descriptor instead.
func (ExpertType) EnumDescriptor() ([]byte, []int) {
	return file_api_expert_v1_expert_proto_rawDescGZIP(), []int{0}
}

type CreateOrUpdateExpertRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url        string     `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Content    string     `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	ExpertType ExpertType `protobuf:"varint,3,opt,name=expert_type,json=expertType,proto3,enum=expert.v1.ExpertType" json:"expert_type,omitempty"`
}

func (x *CreateOrUpdateExpertRequest) Reset() {
	*x = CreateOrUpdateExpertRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_expert_v1_expert_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateOrUpdateExpertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrUpdateExpertRequest) ProtoMessage() {}

func (x *CreateOrUpdateExpertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_expert_v1_expert_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrUpdateExpertRequest.ProtoReflect.Descriptor instead.
func (*CreateOrUpdateExpertRequest) Descriptor() ([]byte, []int) {
	return file_api_expert_v1_expert_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrUpdateExpertRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CreateOrUpdateExpertRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateOrUpdateExpertRequest) GetExpertType() ExpertType {
	if x != nil {
		return x.ExpertType
	}
	return ExpertType_EXPERT_TYPE_UNSPECIFIED
}

type CreateOrUpdateExpertResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExpertId string `protobuf:"bytes,1,opt,name=expert_id,json=expertId,proto3" json:"expert_id,omitempty"`
}

func (x *CreateOrUpdateExpertResponse) Reset() {
	*x = CreateOrUpdateExpertResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_expert_v1_expert_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateOrUpdateExpertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrUpdateExpertResponse) ProtoMessage() {}

func (x *CreateOrUpdateExpertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_expert_v1_expert_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrUpdateExpertResponse.ProtoReflect.Descriptor instead.
func (*CreateOrUpdateExpertResponse) Descriptor() ([]byte, []int) {
	return file_api_expert_v1_expert_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrUpdateExpertResponse) GetExpertId() string {
	if x != nil {
		return x.ExpertId
	}
	return ""
}

type QueryExpertRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url   string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Query string `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"` // We can add conversation history later if needed.
}

func (x *QueryExpertRequest) Reset() {
	*x = QueryExpertRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_expert_v1_expert_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryExpertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryExpertRequest) ProtoMessage() {}

func (x *QueryExpertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_expert_v1_expert_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryExpertRequest.ProtoReflect.Descriptor instead.
func (*QueryExpertRequest) Descriptor() ([]byte, []int) {
	return file_api_expert_v1_expert_proto_rawDescGZIP(), []int{2}
}

func (x *QueryExpertRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *QueryExpertRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type QueryExpertResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Answer string `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
}

func (x *QueryExpertResponse) Reset() {
	*x = QueryExpertResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_expert_v1_expert_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryExpertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryExpertResponse) ProtoMessage() {}

func (x *QueryExpertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_expert_v1_expert_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryExpertResponse.ProtoReflect.Descriptor instead.
func (*QueryExpertResponse) Descriptor() ([]byte, []int) {
	return file_api_expert_v1_expert_proto_rawDescGZIP(), []int{3}
}

func (x *QueryExpertResponse) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

var File_api_expert_v1_expert_proto protoreflect.FileDescriptor

var file_api_expert_v1_expert_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x61, 0x70, 0x69, 0x2f, 0x65, 0x78, 0x70, 0x65, 0x72, 0x74, 0x2f, 0x76, 0x31, 0x2f,
	0x65, 0x78, 0x70, 0x65, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x65, 0x78,
	0x70, 0x65, 0x72, 0x74, 0x2e, 0x76, 0x31, 0x22, 0x81, 0x01, 0x0a, 0x1b, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x78, 0x70, 0x65, 0x72, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x12, 0x36, 0x0a, 0x0b, 0x65, 0x78, 0x70, 0x65, 0x72, 0x74, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x65, 0x78, 0x70, 0x65, 0x72,
	0x74, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x78, 0x70, 0x65, 0x72, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x0a, 0x65, 0x78, 0x70, 0x65, 0x72, 0x74, 0x54, 0x79, 0x70, 0x65, 0x22, 0x3b, 0x0a, 0x1c, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x78, 0x70,
	0x65, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x65,
	0x78, 0x70, 0x65, 0x72, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x65, 0x78, 0x70, 0x65, 0x72, 0x74, 0x49, 0x64, 0x22, 0x3c, 0x0a, 0x12, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x45, 0x78, 0x70, 0x65, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c,
	0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x22, 0x2d, 0x0a, 0x13, 0x51, 0x75, 0x65, 0x72, 0x79, 0x45,
	0x78, 0x70, 0x65, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61,
	0x6e, 0x73, 0x77, 0x65, 0x72, 0x2a, 0x56, 0x0a, 0x0a, 0x45, 0x78, 0x70, 0x65, 0x72, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x17, 0x45, 0x58, 0x50, 0x45, 0x52, 0x54, 0x5f, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00,
	0x12, 0x16, 0x0a, 0x12, 0x45, 0x58, 0x50, 0x45, 0x52, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x53, 0x49, 0x4d, 0x50, 0x4c, 0x45, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x45, 0x58, 0x50, 0x45,
	0x52, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x52, 0x41, 0x47, 0x10, 0x02, 0x32, 0xca, 0x01,
	0x0a, 0x0d, 0x45, 0x78, 0x70, 0x65, 0x72, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x69, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x45, 0x78, 0x70, 0x65, 0x72, 0x74, 0x12, 0x26, 0x2e, 0x65, 0x78, 0x70, 0x65, 0x72, 0x74,
	0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x45, 0x78, 0x70, 0x65, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x27, 0x2e, 0x65, 0x78, 0x70, 0x65, 0x72, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x78, 0x70, 0x65, 0x72, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4e, 0x0a, 0x0b, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x45, 0x78, 0x70, 0x65, 0x72, 0x74, 0x12, 0x1d, 0x2e, 0x65, 0x78, 0x70, 0x65,
	0x72, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x45, 0x78, 0x70, 0x65, 0x72,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x65, 0x78, 0x70, 0x65, 0x72,
	0x74, 0x2e, 0x76, 0x31, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x45, 0x78, 0x70, 0x65, 0x72, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x21, 0x5a, 0x1f, 0x70, 0x6f,
	0x72, 0x74, 0x61, 0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x2f,
	0x70, 0x6b, 0x67, 0x2f, 0x65, 0x78, 0x70, 0x65, 0x72, 0x74, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_expert_v1_expert_proto_rawDescOnce sync.Once
	file_api_expert_v1_expert_proto_rawDescData = file_api_expert_v1_expert_proto_rawDesc
)

func file_api_expert_v1_expert_proto_rawDescGZIP() []byte {
	file_api_expert_v1_expert_proto_rawDescOnce.Do(func() {
		file_api_expert_v1_expert_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_expert_v1_expert_proto_rawDescData)
	})
	return file_api_expert_v1_expert_proto_rawDescData
}

var file_api_expert_v1_expert_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_expert_v1_expert_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_expert_v1_expert_proto_goTypes = []interface{}{
	(ExpertType)(0),                      // 0: expert.v1.ExpertType
	(*CreateOrUpdateExpertRequest)(nil),  // 1: expert.v1.CreateOrUpdateExpertRequest
	(*CreateOrUpdateExpertResponse)(nil), // 2: expert.v1.CreateOrUpdateExpertResponse
	(*QueryExpertRequest)(nil),           // 3: expert.v1.QueryExpertRequest
	(*QueryExpertResponse)(nil),          // 4: expert.v1.QueryExpertResponse
}
var file_api_expert_v1_expert_proto_depIdxs = []int32{
	0, // 0: expert.v1.CreateOrUpdateExpertRequest.expert_type:type_name -> expert.v1.ExpertType
	1, // 1: expert.v1.ExpertService.CreateOrUpdateExpert:input_type -> expert.v1.CreateOrUpdateExpertRequest
	3, // 2: expert.v1.ExpertService.QueryExpert:input_type -> expert.v1.QueryExpertRequest
	2, // 3: expert.v1.ExpertService.CreateOrUpdateExpert:output_type -> expert.v1.CreateOrUpdateExpertResponse
	4, // 4: expert.v1.ExpertService.QueryExpert:output_type -> expert.v1.QueryExpertResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_expert_v1_expert_proto_init() }
func file_api_expert_v1_expert_proto_init() {
	if File_api_expert_v1_expert_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_expert_v1_expert_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateOrUpdateExpertRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_expert_v1_expert_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateOrUpdateExpertResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_expert_v1_expert_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryExpertRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_expert_v1_expert_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryExpertResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_expert_v1_expert_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_expert_v1_expert_proto_goTypes,
		DependencyIndexes: file_api_expert_v1_expert_proto_depIdxs,
		EnumInfos:         file_api_expert_v1_expert_proto_enumTypes,
		MessageInfos:      file_api_expert_v1_expert_proto_msgTypes,
	}.Build()
	File_api_expert_v1_expert_proto = out.File
	file_api_expert_v1_expert_proto_rawDesc = nil
	file_api_expert_v1_expert_proto_goTypes = nil
	file_api_expert_v1_expert_proto_depIdxs = nil
}
